export const combatEquipmentData = [
  {
    rarity: "Légendaire",
    set_name: "Spirit Fulgur",
    family: "Or",
    skydust: "160",
    gem_slots: "3",
    slot_type: "Arme",
    slot_name: "Marteau",
    skill_1: "Recycleur",
    value_1_pct: "5",
    skill_2: "Récupération",
    value_2_pct: "5",
    skill_3: "Prospérité",
    value_3_pct: "15",
    skill_4: "Charognard",
    value_4_pct: "10",
  },
  {
    rarity: "Légendaire",
    set_name: "Spirit Fulgur",
    family: "Or",
    skydust: "160",
    gem_slots: "3",
    slot_type: "Bouclier",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "5",
    skill_2: "Récupération",
    value_2_pct: "5",
    skill_3: "Prospérité",
    value_3_pct: "15",
    skill_4: "Charognard",
    value_4_pct: "10",
  },
  {
    rarity: "Légendaire",
    set_name: "Spirit Fulgur",
    family: "Or",
    skydust: "160",
    gem_slots: "3",
    slot_type: "Ceinture",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "5",
    skill_2: "Récupération",
    value_2_pct: "5",
    skill_3: "Prospérité",
    value_3_pct: "15",
    skill_4: "Charognard",
    value_4_pct: "10",
  },
  {
    rarity: "Légendaire",
    set_name: "Spirit Fulgur",
    family: "Or",
    skydust: "160",
    gem_slots: "3",
    slot_type: "Anneau",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "5",
    skill_2: "Récupération",
    value_2_pct: "5",
    skill_3: "Prospérité",
    value_3_pct: "15",
    skill_4: "Charognard",
    value_4_pct: "10",
  },
  {
    rarity: "Légendaire",
    set_name: "Spirit Fulgur",
    family: "Or",
    skydust: "160",
    gem_slots: "3",
    slot_type: "Bracelet",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "5",
    skill_2: "Récupération",
    value_2_pct: "5",
    skill_3: "Prospérité",
    value_3_pct: "15",
    skill_4: "Charognard",
    value_4_pct: "10",
  },
  {
    rarity: "Légendaire",
    set_name: "Spirit Fulgur",
    family: "Or",
    skydust: "160",
    gem_slots: "3",
    slot_type: "Amulette",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "5",
    skill_2: "Récupération",
    value_2_pct: "5",
    skill_3: "Prospérité",
    value_3_pct: "15",
    skill_4: "Charognard",
    value_4_pct: "10",
  },
  {
    rarity: "Légendaire",
    set_name: "Spirit Fulgur",
    family: "Or",
    skydust: "160",
    gem_slots: "3",
    slot_type: "Casque",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "5",
    skill_2: "Récupération",
    value_2_pct: "5",
    skill_3: "Prospérité",
    value_3_pct: "15",
    skill_4: "Charognard",
    value_4_pct: "10",
  },
  {
    rarity: "Légendaire",
    set_name: "Spirit Fulgur",
    family: "Or",
    skydust: "160",
    gem_slots: "3",
    slot_type: "Gantelet",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "5",
    skill_2: "Récupération",
    value_2_pct: "5",
    skill_3: "Prospérité",
    value_3_pct: "15",
    skill_4: "Charognard",
    value_4_pct: "10",
  },
  {
    rarity: "Légendaire",
    set_name: "Spirit Fulgur",
    family: "Or",
    skydust: "160",
    gem_slots: "3",
    slot_type: "Bottes",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "5",
    skill_2: "Récupération",
    value_2_pct: "5",
    skill_3: "Prospérité",
    value_3_pct: "15",
    skill_4: "Charognard",
    value_4_pct: "10",
  },
  {
    rarity: "Légendaire",
    set_name: "Spirit Zephyr",
    family: "Troupes/Vitesse",
    skydust: "160",
    gem_slots: "3",
    slot_type: "Arme",
    slot_name: "Arc",
    skill_1: "Recruteur",
    value_1_pct: "15",
    skill_2: "Intrépide",
    value_2_pct: "10",
    skill_3: "Bravoure",
    value_3_pct: "10",
    skill_4: "Vitesse",
    value_4_pct: "25",
  },
  {
    rarity: "Légendaire",
    set_name: "Spirit Zephyr",
    family: "Troupes/Vitesse",
    skydust: "160",
    gem_slots: "3",
    slot_type: "Bouclier",
    slot_name: "",
    skill_1: "Recruteur",
    value_1_pct: "15",
    skill_2: "Intrépide",
    value_2_pct: "10",
    skill_3: "Bravoure",
    value_3_pct: "10",
    skill_4: "Vitesse",
    value_4_pct: "25",
  },
  {
    rarity: "Légendaire",
    set_name: "Spirit Zephyr",
    family: "Troupes/Vitesse",
    skydust: "160",
    gem_slots: "3",
    slot_type: "Ceinture",
    slot_name: "",
    skill_1: "Recruteur",
    value_1_pct: "15",
    skill_2: "Intrépide",
    value_2_pct: "10",
    skill_3: "Bravoure",
    value_3_pct: "10",
    skill_4: "Vitesse",
    value_4_pct: "25",
  },
  {
    rarity: "Légendaire",
    set_name: "Spirit Zephyr",
    family: "Troupes/Vitesse",
    skydust: "160",
    gem_slots: "3",
    slot_type: "Anneau",
    slot_name: "",
    skill_1: "Recruteur",
    value_1_pct: "15",
    skill_2: "Intrépide",
    value_2_pct: "10",
    skill_3: "Bravoure",
    value_3_pct: "10",
    skill_4: "Vitesse",
    value_4_pct: "25",
  },
  {
    rarity: "Légendaire",
    set_name: "Spirit Zephyr",
    family: "Troupes/Vitesse",
    skydust: "160",
    gem_slots: "3",
    slot_type: "Bracelet",
    slot_name: "",
    skill_1: "Recruteur",
    value_1_pct: "15",
    skill_2: "Intrépide",
    value_2_pct: "10",
    skill_3: "Bravoure",
    value_3_pct: "10",
    skill_4: "Vitesse",
    value_4_pct: "25",
  },
  {
    rarity: "Légendaire",
    set_name: "Spirit Zephyr",
    family: "Troupes/Vitesse",
    skydust: "160",
    gem_slots: "3",
    slot_type: "Casque",
    slot_name: "",
    skill_1: "Recruteur",
    value_1_pct: "15",
    skill_2: "Intrépide",
    value_2_pct: "10",
    skill_3: "Bravoure",
    value_3_pct: "10",
    skill_4: "Vitesse",
    value_4_pct: "25",
  },
  {
    rarity: "Légendaire",
    set_name: "Spirit Zephyr",
    family: "Troupes/Vitesse",
    skydust: "160",
    gem_slots: "3",
    slot_type: "Gantelet",
    slot_name: "",
    skill_1: "Recruteur",
    value_1_pct: "15",
    skill_2: "Intrépide",
    value_2_pct: "10",
    skill_3: "Bravoure",
    value_3_pct: "10",
    skill_4: "Vitesse",
    value_4_pct: "25",
  },
  {
    rarity: "Légendaire",
    set_name: "Spirit Zephyr",
    family: "Troupes/Vitesse",
    skydust: "160",
    gem_slots: "3",
    slot_type: "Bottes",
    slot_name: "",
    skill_1: "Recruteur",
    value_1_pct: "15",
    skill_2: "Intrépide",
    value_2_pct: "10",
    skill_3: "Bravoure",
    value_3_pct: "10",
    skill_4: "Vitesse",
    value_4_pct: "25",
  },
  {
    rarity: "Légendaire",
    set_name: "Spirit Zephyr",
    family: "Troupes/Vitesse",
    skydust: "160",
    gem_slots: "3",
    slot_type: "Amulette",
    slot_name: "",
    skill_1: "Recruteur",
    value_1_pct: "5",
    skill_2: "Intrépide",
    value_2_pct: "5",
    skill_3: "Bravoure",
    value_3_pct: "15",
    skill_4: "Vitesse",
    value_4_pct: "10",
  },
  {
    rarity: "Légendaire",
    set_name: "Spirit Vanna",
    family: "Défense",
    skydust: "160",
    gem_slots: "3",
    slot_type: "Arme",
    slot_name: "Lance",
    skill_1: "Recycleur",
    value_1_pct: "5",
    skill_2: "Bravoure",
    value_2_pct: "10",
    skill_3: "Défense",
    value_3_pct: "15",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Légendaire",
    set_name: "Spirit Vanna",
    family: "Défense",
    skydust: "160",
    gem_slots: "3",
    slot_type: "Bouclier",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "5",
    skill_2: "Bravoure",
    value_2_pct: "10",
    skill_3: "Défense",
    value_3_pct: "15",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Légendaire",
    set_name: "Spirit Vanna",
    family: "Défense",
    skydust: "160",
    gem_slots: "3",
    slot_type: "Ceinture",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "5",
    skill_2: "Bravoure",
    value_2_pct: "10",
    skill_3: "Défense",
    value_3_pct: "15",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Légendaire",
    set_name: "Spirit Vanna",
    family: "Défense",
    skydust: "160",
    gem_slots: "3",
    slot_type: "Anneau",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "5",
    skill_2: "Bravoure",
    value_2_pct: "10",
    skill_3: "Défense",
    value_3_pct: "15",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Légendaire",
    set_name: "Spirit Vanna",
    family: "Défense",
    skydust: "160",
    gem_slots: "3",
    slot_type: "Bracelet",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "5",
    skill_2: "Bravoure",
    value_2_pct: "10",
    skill_3: "Défense",
    value_3_pct: "15",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Légendaire",
    set_name: "Spirit Vanna",
    family: "Défense",
    skydust: "160",
    gem_slots: "3",
    slot_type: "Amulette",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "5",
    skill_2: "Bravoure",
    value_2_pct: "10",
    skill_3: "Défense",
    value_3_pct: "15",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Légendaire",
    set_name: "Spirit Vanna",
    family: "Défense",
    skydust: "160",
    gem_slots: "3",
    slot_type: "Casque",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "5",
    skill_2: "Bravoure",
    value_2_pct: "10",
    skill_3: "Défense",
    value_3_pct: "15",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Légendaire",
    set_name: "Spirit Vanna",
    family: "Défense",
    skydust: "160",
    gem_slots: "3",
    slot_type: "Gantelet",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "5",
    skill_2: "Bravoure",
    value_2_pct: "10",
    skill_3: "Défense",
    value_3_pct: "15",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Légendaire",
    set_name: "Spirit Vanna",
    family: "Défense",
    skydust: "160",
    gem_slots: "3",
    slot_type: "Bottes",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "5",
    skill_2: "Bravoure",
    value_2_pct: "10",
    skill_3: "Défense",
    value_3_pct: "15",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Légendaire",
    set_name: "Spirit Fyra",
    family: "Attaque",
    skydust: "160",
    gem_slots: "3",
    slot_type: "Arme",
    slot_name: "Hache",
    skill_1: "Attaque",
    value_1_pct: "10",
    skill_2: "Charognard",
    value_2_pct: "10",
    skill_3: "Intrépide",
    value_3_pct: "10",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Légendaire",
    set_name: "Spirit Fyra",
    family: "Attaque",
    skydust: "160",
    gem_slots: "3",
    slot_type: "Bouclier",
    slot_name: "",
    skill_1: "Attaque",
    value_1_pct: "10",
    skill_2: "Charognard",
    value_2_pct: "10",
    skill_3: "Intrépide",
    value_3_pct: "10",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Légendaire",
    set_name: "Spirit Fyra",
    family: "Attaque",
    skydust: "160",
    gem_slots: "3",
    slot_type: "Ceinture",
    slot_name: "",
    skill_1: "Attaque",
    value_1_pct: "10",
    skill_2: "Charognard",
    value_2_pct: "10",
    skill_3: "Intrépide",
    value_3_pct: "10",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Légendaire",
    set_name: "Spirit Fyra",
    family: "Attaque",
    skydust: "160",
    gem_slots: "3",
    slot_type: "Anneau",
    slot_name: "",
    skill_1: "Attaque",
    value_1_pct: "10",
    skill_2: "Charognard",
    value_2_pct: "10",
    skill_3: "Intrépide",
    value_3_pct: "10",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Légendaire",
    set_name: "Spirit Fyra",
    family: "Attaque",
    skydust: "160",
    gem_slots: "3",
    slot_type: "Bracelet",
    slot_name: "",
    skill_1: "Attaque",
    value_1_pct: "10",
    skill_2: "Charognard",
    value_2_pct: "10",
    skill_3: "Intrépide",
    value_3_pct: "10",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Légendaire",
    set_name: "Spirit Fyra",
    family: "Attaque",
    skydust: "160",
    gem_slots: "3",
    slot_type: "Amulette",
    slot_name: "",
    skill_1: "Attaque",
    value_1_pct: "10",
    skill_2: "Charognard",
    value_2_pct: "10",
    skill_3: "Intrépide",
    value_3_pct: "10",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Légendaire",
    set_name: "Spirit Fyra",
    family: "Attaque",
    skydust: "160",
    gem_slots: "3",
    slot_type: "Casque",
    slot_name: "",
    skill_1: "Attaque",
    value_1_pct: "10",
    skill_2: "Charognard",
    value_2_pct: "10",
    skill_3: "Intrépide",
    value_3_pct: "10",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Légendaire",
    set_name: "Spirit Fyra",
    family: "Attaque",
    skydust: "160",
    gem_slots: "3",
    slot_type: "Gantelet",
    slot_name: "",
    skill_1: "Attaque",
    value_1_pct: "10",
    skill_2: "Charognard",
    value_2_pct: "10",
    skill_3: "Intrépide",
    value_3_pct: "10",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Légendaire",
    set_name: "Spirit Fyra",
    family: "Attaque",
    skydust: "160",
    gem_slots: "3",
    slot_type: "Bottes",
    slot_name: "",
    skill_1: "Attaque",
    value_1_pct: "10",
    skill_2: "Charognard",
    value_2_pct: "10",
    skill_3: "Intrépide",
    value_3_pct: "10",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Mythique",
    set_name: "Shark",
    family: "Or",
    skydust: "120",
    gem_slots: "2",
    slot_type: "Arme",
    slot_name: "Sabre",
    skill_1: "Recycleur",
    value_1_pct: "3",
    skill_2: "Récupération",
    value_2_pct: "1",
    skill_3: "Prospérité",
    value_3_pct: "12",
    skill_4: "Charognard",
    value_4_pct: "4",
  },
  {
    rarity: "Mythique",
    set_name: "Shark",
    family: "Or",
    skydust: "120",
    gem_slots: "2",
    slot_type: "Bouclier",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "3",
    skill_2: "Récupération",
    value_2_pct: "1",
    skill_3: "Prospérité",
    value_3_pct: "12",
    skill_4: "Charognard",
    value_4_pct: "4",
  },
  {
    rarity: "Mythique",
    set_name: "Shark",
    family: "Or",
    skydust: "120",
    gem_slots: "2",
    slot_type: "Ceinture",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "3",
    skill_2: "Récupération",
    value_2_pct: "1",
    skill_3: "Prospérité",
    value_3_pct: "12",
    skill_4: "Charognard",
    value_4_pct: "4",
  },
  {
    rarity: "Mythique",
    set_name: "Shark",
    family: "Or",
    skydust: "120",
    gem_slots: "2",
    slot_type: "Anneau",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "1",
    skill_2: "Récupération",
    value_2_pct: "4",
    skill_3: "Prospérité",
    value_3_pct: "9",
    skill_4: "Charognard",
    value_4_pct: "4",
  },
  {
    rarity: "Mythique",
    set_name: "Shark",
    family: "Or",
    skydust: "120",
    gem_slots: "2",
    slot_type: "Bracelet",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "1",
    skill_2: "Récupération",
    value_2_pct: "4",
    skill_3: "Prospérité",
    value_3_pct: "9",
    skill_4: "Charognard",
    value_4_pct: "4",
  },
  {
    rarity: "Mythique",
    set_name: "Shark",
    family: "Or",
    skydust: "120",
    gem_slots: "2",
    slot_type: "Amulette",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "1",
    skill_2: "Récupération",
    value_2_pct: "4",
    skill_3: "Prospérité",
    value_3_pct: "9",
    skill_4: "Charognard",
    value_4_pct: "4",
  },
  {
    rarity: "Mythique",
    set_name: "Shark",
    family: "Or",
    skydust: "120",
    gem_slots: "2",
    slot_type: "Casque",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "4",
    skill_2: "Récupération",
    value_2_pct: "2",
    skill_3: "Prospérité",
    value_3_pct: "3",
    skill_4: "Charognard",
    value_4_pct: "6",
  },
  {
    rarity: "Mythique",
    set_name: "Shark",
    family: "Or",
    skydust: "120",
    gem_slots: "2",
    slot_type: "Gantelet",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "4",
    skill_2: "Récupération",
    value_2_pct: "2",
    skill_3: "Prospérité",
    value_3_pct: "3",
    skill_4: "Charognard",
    value_4_pct: "6",
  },
  {
    rarity: "Mythique",
    set_name: "Shark",
    family: "Or",
    skydust: "120",
    gem_slots: "2",
    slot_type: "Bottes",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "4",
    skill_2: "Récupération",
    value_2_pct: "2",
    skill_3: "Prospérité",
    value_3_pct: "3",
    skill_4: "Charognard",
    value_4_pct: "6",
  },
  {
    rarity: "Mythique",
    set_name: "Owl",
    family: "Troupes/Vitesse",
    skydust: "120",
    gem_slots: "2",
    slot_type: "Arme",
    slot_name: "Arc",
    skill_1: "Recruteur",
    value_1_pct: "12",
    skill_2: "Intrépide",
    value_2_pct: "6",
    skill_3: "Bravoure",
    value_3_pct: "4",
    skill_4: "Vitesse",
    value_4_pct: "5",
  },
  {
    rarity: "Mythique",
    set_name: "Owl",
    family: "Troupes/Vitesse",
    skydust: "120",
    gem_slots: "2",
    slot_type: "Bouclier",
    slot_name: "",
    skill_1: "Recruteur",
    value_1_pct: "12",
    skill_2: "Intrépide",
    value_2_pct: "6",
    skill_3: "Bravoure",
    value_3_pct: "4",
    skill_4: "Vitesse",
    value_4_pct: "5",
  },
  {
    rarity: "Mythique",
    set_name: "Owl",
    family: "Troupes/Vitesse",
    skydust: "120",
    gem_slots: "2",
    slot_type: "Ceinture",
    slot_name: "",
    skill_1: "Recruteur",
    value_1_pct: "12",
    skill_2: "Intrépide",
    value_2_pct: "6",
    skill_3: "Bravoure",
    value_3_pct: "4",
    skill_4: "Vitesse",
    value_4_pct: "5",
  },
  {
    rarity: "Mythique",
    set_name: "Owl",
    family: "Troupes/Vitesse",
    skydust: "120",
    gem_slots: "2",
    slot_type: "Anneau",
    slot_name: "",
    skill_1: "Recruteur",
    value_1_pct: "3",
    skill_2: "Intrépide",
    value_2_pct: "6",
    skill_3: "Bravoure",
    value_3_pct: "4",
    skill_4: "Vitesse",
    value_4_pct: "20",
  },
  {
    rarity: "Mythique",
    set_name: "Owl",
    family: "Troupes/Vitesse",
    skydust: "120",
    gem_slots: "2",
    slot_type: "Bracelet",
    slot_name: "",
    skill_1: "Recruteur",
    value_1_pct: "3",
    skill_2: "Intrépide",
    value_2_pct: "6",
    skill_3: "Bravoure",
    value_3_pct: "4",
    skill_4: "Vitesse",
    value_4_pct: "20",
  },
  {
    rarity: "Mythique",
    set_name: "Owl",
    family: "Troupes/Vitesse",
    skydust: "120",
    gem_slots: "2",
    slot_type: "Amulette",
    slot_name: "",
    skill_1: "Recruteur",
    value_1_pct: "3",
    skill_2: "Intrépide",
    value_2_pct: "6",
    skill_3: "Bravoure",
    value_3_pct: "4",
    skill_4: "Vitesse",
    value_4_pct: "20",
  },
  {
    rarity: "Mythique",
    set_name: "Owl",
    family: "Troupes/Vitesse",
    skydust: "120",
    gem_slots: "2",
    slot_type: "Casque",
    slot_name: "",
    skill_1: "Recruteur",
    value_1_pct: "9",
    skill_2: "Intrépide",
    value_2_pct: "2",
    skill_3: "Bravoure",
    value_3_pct: "10",
    skill_4: "Vitesse",
    value_4_pct: "10",
  },
  {
    rarity: "Mythique",
    set_name: "Owl",
    family: "Troupes/Vitesse",
    skydust: "120",
    gem_slots: "2",
    slot_type: "Gantelet",
    slot_name: "",
    skill_1: "Recruteur",
    value_1_pct: "9",
    skill_2: "Intrépide",
    value_2_pct: "2",
    skill_3: "Bravoure",
    value_3_pct: "10",
    skill_4: "Vitesse",
    value_4_pct: "10",
  },
  {
    rarity: "Mythique",
    set_name: "Owl",
    family: "Troupes/Vitesse",
    skydust: "120",
    gem_slots: "2",
    slot_type: "Bottes",
    slot_name: "",
    skill_1: "Recruteur",
    value_1_pct: "9",
    skill_2: "Intrépide",
    value_2_pct: "2",
    skill_3: "Bravoure",
    value_3_pct: "10",
    skill_4: "Vitesse",
    value_4_pct: "10",
  },
  {
    rarity: "Mythique",
    set_name: "Snake",
    family: "Défense",
    skydust: "120",
    gem_slots: "2",
    slot_type: "Arme",
    slot_name: "Lance",
    skill_1: "Recycleur",
    value_1_pct: "2",
    skill_2: "Bravoure",
    value_2_pct: "6",
    skill_3: "Défense",
    value_3_pct: "12",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Mythique",
    set_name: "Snake",
    family: "Défense",
    skydust: "120",
    gem_slots: "2",
    slot_type: "Bouclier",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "2",
    skill_2: "Bravoure",
    value_2_pct: "6",
    skill_3: "Défense",
    value_3_pct: "12",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Mythique",
    set_name: "Snake",
    family: "Défense",
    skydust: "120",
    gem_slots: "2",
    slot_type: "Ceinture",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "2",
    skill_2: "Bravoure",
    value_2_pct: "6",
    skill_3: "Défense",
    value_3_pct: "12",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Mythique",
    set_name: "Snake",
    family: "Défense",
    skydust: "120",
    gem_slots: "2",
    slot_type: "Anneau",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "4",
    skill_2: "Bravoure",
    value_2_pct: "6",
    skill_3: "Défense",
    value_3_pct: "6",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Mythique",
    set_name: "Snake",
    family: "Défense",
    skydust: "120",
    gem_slots: "2",
    slot_type: "Bracelet",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "4",
    skill_2: "Bravoure",
    value_2_pct: "6",
    skill_3: "Défense",
    value_3_pct: "6",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Mythique",
    set_name: "Snake",
    family: "Défense",
    skydust: "120",
    gem_slots: "2",
    slot_type: "Amulette",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "4",
    skill_2: "Bravoure",
    value_2_pct: "6",
    skill_3: "Défense",
    value_3_pct: "6",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Mythique",
    set_name: "Snake",
    family: "Défense",
    skydust: "120",
    gem_slots: "2",
    slot_type: "Casque",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "2",
    skill_2: "Bravoure",
    value_2_pct: "8",
    skill_3: "Défense",
    value_3_pct: "9",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Mythique",
    set_name: "Snake",
    family: "Défense",
    skydust: "120",
    gem_slots: "2",
    slot_type: "Gantelet",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "2",
    skill_2: "Bravoure",
    value_2_pct: "8",
    skill_3: "Défense",
    value_3_pct: "9",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Mythique",
    set_name: "Snake",
    family: "Défense",
    skydust: "120",
    gem_slots: "2",
    slot_type: "Bottes",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "2",
    skill_2: "Bravoure",
    value_2_pct: "8",
    skill_3: "Défense",
    value_3_pct: "9",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Mythique",
    set_name: "Almaty",
    family: "Attaque",
    skydust: "120",
    gem_slots: "2",
    slot_type: "Arme",
    slot_name: "Épée",
    skill_1: "Attaque",
    value_1_pct: "8",
    skill_2: "Charognard",
    value_2_pct: "6",
    skill_3: "Intrépide",
    value_3_pct: "4",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Mythique",
    set_name: "Almaty",
    family: "Attaque",
    skydust: "120",
    gem_slots: "2",
    slot_type: "Bouclier",
    slot_name: "",
    skill_1: "Attaque",
    value_1_pct: "8",
    skill_2: "Charognard",
    value_2_pct: "6",
    skill_3: "Intrépide",
    value_3_pct: "4",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Mythique",
    set_name: "Almaty",
    family: "Attaque",
    skydust: "120",
    gem_slots: "2",
    slot_type: "Ceinture",
    slot_name: "",
    skill_1: "Attaque",
    value_1_pct: "8",
    skill_2: "Charognard",
    value_2_pct: "6",
    skill_3: "Intrépide",
    value_3_pct: "4",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Mythique",
    set_name: "Almaty",
    family: "Attaque",
    skydust: "120",
    gem_slots: "2",
    slot_type: "Anneau",
    slot_name: "",
    skill_1: "Attaque",
    value_1_pct: "4",
    skill_2: "Charognard",
    value_2_pct: "8",
    skill_3: "Intrépide",
    value_3_pct: "6",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Mythique",
    set_name: "Almaty",
    family: "Attaque",
    skydust: "120",
    gem_slots: "2",
    slot_type: "Bracelet",
    slot_name: "",
    skill_1: "Attaque",
    value_1_pct: "4",
    skill_2: "Charognard",
    value_2_pct: "8",
    skill_3: "Intrépide",
    value_3_pct: "6",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Mythique",
    set_name: "Almaty",
    family: "Attaque",
    skydust: "120",
    gem_slots: "2",
    slot_type: "Amulette",
    slot_name: "",
    skill_1: "Attaque",
    value_1_pct: "4",
    skill_2: "Charognard",
    value_2_pct: "8",
    skill_3: "Intrépide",
    value_3_pct: "6",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Mythique",
    set_name: "Almaty",
    family: "Attaque",
    skydust: "120",
    gem_slots: "2",
    slot_type: "Casque",
    slot_name: "",
    skill_1: "Attaque",
    value_1_pct: "6",
    skill_2: "Charognard",
    value_2_pct: "4",
    skill_3: "Intrépide",
    value_3_pct: "8",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Mythique",
    set_name: "Almaty",
    family: "Attaque",
    skydust: "120",
    gem_slots: "2",
    slot_type: "Gantelet",
    slot_name: "",
    skill_1: "Attaque",
    value_1_pct: "6",
    skill_2: "Charognard",
    value_2_pct: "4",
    skill_3: "Intrépide",
    value_3_pct: "8",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Mythique",
    set_name: "Almaty",
    family: "Attaque",
    skydust: "120",
    gem_slots: "2",
    slot_type: "Bottes",
    slot_name: "",
    skill_1: "Attaque",
    value_1_pct: "6",
    skill_2: "Charognard",
    value_2_pct: "4",
    skill_3: "Intrépide",
    value_3_pct: "8",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Épique",
    set_name: "Shopkeeper",
    family: "Or",
    skydust: "30",
    gem_slots: "1",
    slot_type: "Arme",
    slot_name: "Sabre",
    skill_1: "Recycleur",
    value_1_pct: "2",
    skill_2: "Récupération",
    value_2_pct: "0",
    skill_3: "Prospérité",
    value_3_pct: "9",
    skill_4: "Charognard",
    value_4_pct: "2",
  },
  {
    rarity: "Épique",
    set_name: "Shopkeeper",
    family: "Or",
    skydust: "30",
    gem_slots: "1",
    slot_type: "Bouclier",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "2",
    skill_2: "Récupération",
    value_2_pct: "0",
    skill_3: "Prospérité",
    value_3_pct: "9",
    skill_4: "Charognard",
    value_4_pct: "2",
  },
  {
    rarity: "Épique",
    set_name: "Shopkeeper",
    family: "Or",
    skydust: "30",
    gem_slots: "1",
    slot_type: "Ceinture",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "2",
    skill_2: "Récupération",
    value_2_pct: "0",
    skill_3: "Prospérité",
    value_3_pct: "9",
    skill_4: "Charognard",
    value_4_pct: "2",
  },
  {
    rarity: "Épique",
    set_name: "Shopkeeper",
    family: "Or",
    skydust: "30",
    gem_slots: "1",
    slot_type: "Anneau",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "0",
    skill_2: "Récupération",
    value_2_pct: "3",
    skill_3: "Prospérité",
    value_3_pct: "6",
    skill_4: "Charognard",
    value_4_pct: "2",
  },
  {
    rarity: "Épique",
    set_name: "Shopkeeper",
    family: "Or",
    skydust: "30",
    gem_slots: "1",
    slot_type: "Bracelet",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "0",
    skill_2: "Récupération",
    value_2_pct: "3",
    skill_3: "Prospérité",
    value_3_pct: "6",
    skill_4: "Charognard",
    value_4_pct: "2",
  },
  {
    rarity: "Épique",
    set_name: "Shopkeeper",
    family: "Or",
    skydust: "30",
    gem_slots: "1",
    slot_type: "Amulette",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "0",
    skill_2: "Récupération",
    value_2_pct: "3",
    skill_3: "Prospérité",
    value_3_pct: "6",
    skill_4: "Charognard",
    value_4_pct: "2",
  },
  {
    rarity: "Épique",
    set_name: "Royal Archer",
    family: "Troupes/Vitesse",
    skydust: "30",
    gem_slots: "1",
    slot_type: "Arme",
    slot_name: "Arc",
    skill_1: "Recruteur",
    value_1_pct: "9",
    skill_2: "Intrépide",
    value_2_pct: "4",
    skill_3: "Bravoure",
    value_3_pct: "2",
    skill_4: "Vitesse",
    value_4_pct: "0",
  },
  {
    rarity: "Épique",
    set_name: "Royal Archer",
    family: "Troupes/Vitesse",
    skydust: "30",
    gem_slots: "1",
    slot_type: "Bouclier",
    slot_name: "",
    skill_1: "Recruteur",
    value_1_pct: "9",
    skill_2: "Intrépide",
    value_2_pct: "4",
    skill_3: "Bravoure",
    value_3_pct: "2",
    skill_4: "Vitesse",
    value_4_pct: "0",
  },
  {
    rarity: "Épique",
    set_name: "Royal Archer",
    family: "Troupes/Vitesse",
    skydust: "30",
    gem_slots: "1",
    slot_type: "Ceinture",
    slot_name: "",
    skill_1: "Recruteur",
    value_1_pct: "9",
    skill_2: "Intrépide",
    value_2_pct: "4",
    skill_3: "Bravoure",
    value_3_pct: "2",
    skill_4: "Vitesse",
    value_4_pct: "0",
  },
  {
    rarity: "Épique",
    set_name: "Royal Archer",
    family: "Troupes/Vitesse",
    skydust: "30",
    gem_slots: "1",
    slot_type: "Anneau",
    slot_name: "",
    skill_1: "Recruteur",
    value_1_pct: "0",
    skill_2: "Intrépide",
    value_2_pct: "4",
    skill_3: "Bravoure",
    value_3_pct: "2",
    skill_4: "Vitesse",
    value_4_pct: "15",
  },
  {
    rarity: "Épique",
    set_name: "Royal Archer",
    family: "Troupes/Vitesse",
    skydust: "30",
    gem_slots: "1",
    slot_type: "Bracelet",
    slot_name: "",
    skill_1: "Recruteur",
    value_1_pct: "0",
    skill_2: "Intrépide",
    value_2_pct: "4",
    skill_3: "Bravoure",
    value_3_pct: "2",
    skill_4: "Vitesse",
    value_4_pct: "15",
  },
  {
    rarity: "Épique",
    set_name: "Royal Archer",
    family: "Troupes/Vitesse",
    skydust: "30",
    gem_slots: "1",
    slot_type: "Amulette",
    slot_name: "",
    skill_1: "Recruteur",
    value_1_pct: "0",
    skill_2: "Intrépide",
    value_2_pct: "4",
    skill_3: "Bravoure",
    value_3_pct: "2",
    skill_4: "Vitesse",
    value_4_pct: "15",
  },
  {
    rarity: "Épique",
    set_name: "Knight",
    family: "Défense",
    skydust: "30",
    gem_slots: "1",
    slot_type: "Arme",
    slot_name: "Hallebarde",
    skill_1: "Recycleur",
    value_1_pct: "1",
    skill_2: "Bravoure",
    value_2_pct: "4",
    skill_3: "Défense",
    value_3_pct: "9",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Épique",
    set_name: "Knight",
    family: "Défense",
    skydust: "30",
    gem_slots: "1",
    slot_type: "Bouclier",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "1",
    skill_2: "Bravoure",
    value_2_pct: "4",
    skill_3: "Défense",
    value_3_pct: "9",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Épique",
    set_name: "Knight",
    family: "Défense",
    skydust: "30",
    gem_slots: "1",
    slot_type: "Ceinture",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "1",
    skill_2: "Bravoure",
    value_2_pct: "4",
    skill_3: "Défense",
    value_3_pct: "9",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Épique",
    set_name: "Knight",
    family: "Défense",
    skydust: "30",
    gem_slots: "1",
    slot_type: "Anneau",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "3",
    skill_2: "Bravoure",
    value_2_pct: "4",
    skill_3: "Défense",
    value_3_pct: "3",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Épique",
    set_name: "Knight",
    family: "Défense",
    skydust: "30",
    gem_slots: "1",
    slot_type: "Bracelet",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "3",
    skill_2: "Bravoure",
    value_2_pct: "4",
    skill_3: "Défense",
    value_3_pct: "3",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Épique",
    set_name: "Knight",
    family: "Défense",
    skydust: "30",
    gem_slots: "1",
    slot_type: "Amulette",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "3",
    skill_2: "Bravoure",
    value_2_pct: "4",
    skill_3: "Défense",
    value_3_pct: "3",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Épique",
    set_name: "Royal Guard",
    family: "Attaque",
    skydust: "30",
    gem_slots: "1",
    slot_type: "Arme",
    slot_name: "Épée",
    skill_1: "Attaque",
    value_1_pct: "6",
    skill_2: "Charognard",
    value_2_pct: "4",
    skill_3: "Intrépide",
    value_3_pct: "2",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Épique",
    set_name: "Royal Guard",
    family: "Attaque",
    skydust: "30",
    gem_slots: "1",
    slot_type: "Bouclier",
    slot_name: "",
    skill_1: "Attaque",
    value_1_pct: "6",
    skill_2: "Charognard",
    value_2_pct: "4",
    skill_3: "Intrépide",
    value_3_pct: "2",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Épique",
    set_name: "Royal Guard",
    family: "Attaque",
    skydust: "30",
    gem_slots: "1",
    slot_type: "Ceinture",
    slot_name: "",
    skill_1: "Attaque",
    value_1_pct: "6",
    skill_2: "Charognard",
    value_2_pct: "4",
    skill_3: "Intrépide",
    value_3_pct: "2",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Épique",
    set_name: "Royal Guard",
    family: "Attaque",
    skydust: "30",
    gem_slots: "1",
    slot_type: "Anneau",
    slot_name: "",
    skill_1: "Attaque",
    value_1_pct: "2",
    skill_2: "Charognard",
    value_2_pct: "6",
    skill_3: "Intrépide",
    value_3_pct: "4",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Épique",
    set_name: "Royal Guard",
    family: "Attaque",
    skydust: "30",
    gem_slots: "1",
    slot_type: "Bracelet",
    slot_name: "",
    skill_1: "Attaque",
    value_1_pct: "2",
    skill_2: "Charognard",
    value_2_pct: "6",
    skill_3: "Intrépide",
    value_3_pct: "4",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Épique",
    set_name: "Royal Guard",
    family: "Attaque",
    skydust: "30",
    gem_slots: "1",
    slot_type: "Amulette",
    slot_name: "",
    skill_1: "Attaque",
    value_1_pct: "2",
    skill_2: "Charognard",
    value_2_pct: "6",
    skill_3: "Intrépide",
    value_3_pct: "4",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Rare",
    set_name: "Smuggler",
    family: "Or",
    skydust: "10",
    gem_slots: "0",
    slot_type: "Arme",
    slot_name: "Sabre",
    skill_1: "Recycleur",
    value_1_pct: "1",
    skill_2: "Récupération",
    value_2_pct: "0",
    skill_3: "Prospérité",
    value_3_pct: "6",
    skill_4: "Charognard",
    value_4_pct: "0",
  },
  {
    rarity: "Rare",
    set_name: "Smuggler",
    family: "Or",
    skydust: "10",
    gem_slots: "0",
    slot_type: "Bouclier",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "1",
    skill_2: "Récupération",
    value_2_pct: "0",
    skill_3: "Prospérité",
    value_3_pct: "6",
    skill_4: "Charognard",
    value_4_pct: "0",
  },
  {
    rarity: "Rare",
    set_name: "Smuggler",
    family: "Or",
    skydust: "10",
    gem_slots: "0",
    slot_type: "Ceinture",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "1",
    skill_2: "Récupération",
    value_2_pct: "0",
    skill_3: "Prospérité",
    value_3_pct: "6",
    skill_4: "Charognard",
    value_4_pct: "0",
  },
  {
    rarity: "Rare",
    set_name: "Smuggler",
    family: "Or",
    skydust: "10",
    gem_slots: "0",
    slot_type: "Anneau",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "0",
    skill_2: "Récupération",
    value_2_pct: "2",
    skill_3: "Prospérité",
    value_3_pct: "3",
    skill_4: "Charognard",
    value_4_pct: "0",
  },
  {
    rarity: "Rare",
    set_name: "Smuggler",
    family: "Or",
    skydust: "10",
    gem_slots: "0",
    slot_type: "Bracelet",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "0",
    skill_2: "Récupération",
    value_2_pct: "2",
    skill_3: "Prospérité",
    value_3_pct: "3",
    skill_4: "Charognard",
    value_4_pct: "0",
  },
  {
    rarity: "Rare",
    set_name: "Smuggler",
    family: "Or",
    skydust: "10",
    gem_slots: "0",
    slot_type: "Amulette",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "0",
    skill_2: "Récupération",
    value_2_pct: "2",
    skill_3: "Prospérité",
    value_3_pct: "3",
    skill_4: "Charognard",
    value_4_pct: "0",
  },
  {
    rarity: "Rare",
    set_name: "Hunter",
    family: "Troupes/Vitesse",
    skydust: "10",
    gem_slots: "0",
    slot_type: "Arme",
    slot_name: "Arc",
    skill_1: "Recruteur",
    value_1_pct: "6",
    skill_2: "Intrépide",
    value_2_pct: "2",
    skill_3: "Bravoure",
    value_3_pct: "0",
    skill_4: "Vitesse",
    value_4_pct: "0",
  },
  {
    rarity: "Rare",
    set_name: "Hunter",
    family: "Troupes/Vitesse",
    skydust: "10",
    gem_slots: "0",
    slot_type: "Bouclier",
    slot_name: "",
    skill_1: "Recruteur",
    value_1_pct: "6",
    skill_2: "Intrépide",
    value_2_pct: "2",
    skill_3: "Bravoure",
    value_3_pct: "0",
    skill_4: "Vitesse",
    value_4_pct: "0",
  },
  {
    rarity: "Rare",
    set_name: "Hunter",
    family: "Troupes/Vitesse",
    skydust: "10",
    gem_slots: "0",
    slot_type: "Ceinture",
    slot_name: "",
    skill_1: "Recruteur",
    value_1_pct: "6",
    skill_2: "Intrépide",
    value_2_pct: "2",
    skill_3: "Bravoure",
    value_3_pct: "0",
    skill_4: "Vitesse",
    value_4_pct: "0",
  },
  {
    rarity: "Rare",
    set_name: "Hunter",
    family: "Troupes/Vitesse",
    skydust: "10",
    gem_slots: "0",
    slot_type: "Anneau",
    slot_name: "",
    skill_1: "Recruteur",
    value_1_pct: "0",
    skill_2: "Intrépide",
    value_2_pct: "2",
    skill_3: "Bravoure",
    value_3_pct: "0",
    skill_4: "Vitesse",
    value_4_pct: "10",
  },
  {
    rarity: "Rare",
    set_name: "Hunter",
    family: "Troupes/Vitesse",
    skydust: "10",
    gem_slots: "0",
    slot_type: "Bracelet",
    slot_name: "",
    skill_1: "Recruteur",
    value_1_pct: "0",
    skill_2: "Intrépide",
    value_2_pct: "2",
    skill_3: "Bravoure",
    value_3_pct: "0",
    skill_4: "Vitesse",
    value_4_pct: "10",
  },
  {
    rarity: "Rare",
    set_name: "Hunter",
    family: "Troupes/Vitesse",
    skydust: "10",
    gem_slots: "0",
    slot_type: "Amulette",
    slot_name: "",
    skill_1: "Recruteur",
    value_1_pct: "0",
    skill_2: "Intrépide",
    value_2_pct: "2",
    skill_3: "Bravoure",
    value_3_pct: "0",
    skill_4: "Vitesse",
    value_4_pct: "10",
  },
  {
    rarity: "Rare",
    set_name: "Adventurer",
    family: "Défense",
    skydust: "10",
    gem_slots: "0",
    slot_type: "Arme",
    slot_name: "Épée",
    skill_1: "Recycleur",
    value_1_pct: "0",
    skill_2: "Bravoure",
    value_2_pct: "2",
    skill_3: "Défense",
    value_3_pct: "6",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Rare",
    set_name: "Adventurer",
    family: "Défense",
    skydust: "10",
    gem_slots: "0",
    slot_type: "Bouclier",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "0",
    skill_2: "Bravoure",
    value_2_pct: "2",
    skill_3: "Défense",
    value_3_pct: "6",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Rare",
    set_name: "Adventurer",
    family: "Défense",
    skydust: "10",
    gem_slots: "0",
    slot_type: "Ceinture",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "0",
    skill_2: "Bravoure",
    value_2_pct: "2",
    skill_3: "Défense",
    value_3_pct: "6",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Rare",
    set_name: "Adventurer",
    family: "Défense",
    skydust: "10",
    gem_slots: "0",
    slot_type: "Anneau",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "2",
    skill_2: "Bravoure",
    value_2_pct: "2",
    skill_3: "Défense",
    value_3_pct: "0",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Rare",
    set_name: "Adventurer",
    family: "Défense",
    skydust: "10",
    gem_slots: "0",
    slot_type: "Bracelet",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "2",
    skill_2: "Bravoure",
    value_2_pct: "2",
    skill_3: "Défense",
    value_3_pct: "0",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Rare",
    set_name: "Adventurer",
    family: "Défense",
    skydust: "10",
    gem_slots: "0",
    slot_type: "Amulette",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "2",
    skill_2: "Bravoure",
    value_2_pct: "2",
    skill_3: "Défense",
    value_3_pct: "0",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Rare",
    set_name: "Soldier",
    family: "Attaque",
    skydust: "10",
    gem_slots: "0",
    slot_type: "Arme",
    slot_name: "Lance",
    skill_1: "Attaque",
    value_1_pct: "4",
    skill_2: "Charognard",
    value_2_pct: "2",
    skill_3: "Intrépide",
    value_3_pct: "0",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Rare",
    set_name: "Soldier",
    family: "Attaque",
    skydust: "10",
    gem_slots: "0",
    slot_type: "Bouclier",
    slot_name: "",
    skill_1: "Attaque",
    value_1_pct: "4",
    skill_2: "Charognard",
    value_2_pct: "2",
    skill_3: "Intrépide",
    value_3_pct: "0",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Rare",
    set_name: "Soldier",
    family: "Attaque",
    skydust: "10",
    gem_slots: "0",
    slot_type: "Ceinture",
    slot_name: "",
    skill_1: "Attaque",
    value_1_pct: "4",
    skill_2: "Charognard",
    value_2_pct: "2",
    skill_3: "Intrépide",
    value_3_pct: "0",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Rare",
    set_name: "Soldier",
    family: "Attaque",
    skydust: "10",
    gem_slots: "0",
    slot_type: "Anneau",
    slot_name: "",
    skill_1: "Attaque",
    value_1_pct: "0",
    skill_2: "Charognard",
    value_2_pct: "4",
    skill_3: "Intrépide",
    value_3_pct: "2",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Rare",
    set_name: "Soldier",
    family: "Attaque",
    skydust: "10",
    gem_slots: "0",
    slot_type: "Bracelet",
    slot_name: "",
    skill_1: "Attaque",
    value_1_pct: "0",
    skill_2: "Charognard",
    value_2_pct: "4",
    skill_3: "Intrépide",
    value_3_pct: "2",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Rare",
    set_name: "Soldier",
    family: "Attaque",
    skydust: "10",
    gem_slots: "0",
    slot_type: "Amulette",
    slot_name: "",
    skill_1: "Attaque",
    value_1_pct: "0",
    skill_2: "Charognard",
    value_2_pct: "4",
    skill_3: "Intrépide",
    value_3_pct: "2",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Commun",
    set_name: "Thief",
    family: "Or",
    skydust: "3",
    gem_slots: "0",
    slot_type: "Arme",
    slot_name: "Sabre",
    skill_1: "Recycleur",
    value_1_pct: "0",
    skill_2: "Récupération",
    value_2_pct: "0",
    skill_3: "Prospérité",
    value_3_pct: "3",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Commun",
    set_name: "Thief",
    family: "Or",
    skydust: "3",
    gem_slots: "0",
    slot_type: "Bouclier",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "0",
    skill_2: "Récupération",
    value_2_pct: "0",
    skill_3: "Prospérité",
    value_3_pct: "3",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Commun",
    set_name: "Thief",
    family: "Or",
    skydust: "3",
    gem_slots: "0",
    slot_type: "Ceinture",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "0",
    skill_2: "Récupération",
    value_2_pct: "0",
    skill_3: "Prospérité",
    value_3_pct: "3",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Commun",
    set_name: "Thief",
    family: "Or",
    skydust: "3",
    gem_slots: "0",
    slot_type: "Anneau",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "1",
    skill_2: "Récupération",
    value_2_pct: "0",
    skill_3: "Prospérité",
    value_3_pct: "0",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Commun",
    set_name: "Thief",
    family: "Or",
    skydust: "3",
    gem_slots: "0",
    slot_type: "Bracelet",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "1",
    skill_2: "Récupération",
    value_2_pct: "0",
    skill_3: "Prospérité",
    value_3_pct: "0",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Commun",
    set_name: "Thief",
    family: "Or",
    skydust: "3",
    gem_slots: "0",
    slot_type: "Amulette",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "1",
    skill_2: "Récupération",
    value_2_pct: "0",
    skill_3: "Prospérité",
    value_3_pct: "0",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Commun",
    set_name: "Bard",
    family: "Troupes/Vitesse",
    skydust: "3",
    gem_slots: "0",
    slot_type: "Arme",
    slot_name: "Arc",
    skill_1: "Recruteur",
    value_1_pct: "3",
    skill_2: "Intrépide",
    value_2_pct: "0",
    skill_3: "Vitesse",
    value_3_pct: "0",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Commun",
    set_name: "Bard",
    family: "Troupes/Vitesse",
    skydust: "3",
    gem_slots: "0",
    slot_type: "Bouclier",
    slot_name: "",
    skill_1: "Recruteur",
    value_1_pct: "3",
    skill_2: "Intrépide",
    value_2_pct: "0",
    skill_3: "Vitesse",
    value_3_pct: "0",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Commun",
    set_name: "Bard",
    family: "Troupes/Vitesse",
    skydust: "3",
    gem_slots: "0",
    slot_type: "Ceinture",
    slot_name: "",
    skill_1: "Recruteur",
    value_1_pct: "3",
    skill_2: "Intrépide",
    value_2_pct: "0",
    skill_3: "Vitesse",
    value_3_pct: "0",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Commun",
    set_name: "Bard",
    family: "Troupes/Vitesse",
    skydust: "3",
    gem_slots: "0",
    slot_type: "Anneau",
    slot_name: "",
    skill_1: "Recruteur",
    value_1_pct: "0",
    skill_2: "Intrépide",
    value_2_pct: "0",
    skill_3: "Vitesse",
    value_3_pct: "5",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Commun",
    set_name: "Bard",
    family: "Troupes/Vitesse",
    skydust: "3",
    gem_slots: "0",
    slot_type: "Bracelet",
    slot_name: "",
    skill_1: "Recruteur",
    value_1_pct: "0",
    skill_2: "Intrépide",
    value_2_pct: "0",
    skill_3: "Vitesse",
    value_3_pct: "5",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Commun",
    set_name: "Bard",
    family: "Troupes/Vitesse",
    skydust: "3",
    gem_slots: "0",
    slot_type: "Amulette",
    slot_name: "",
    skill_1: "Recruteur",
    value_1_pct: "0",
    skill_2: "Intrépide",
    value_2_pct: "0",
    skill_3: "Vitesse",
    value_3_pct: "5",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Commun",
    set_name: "Journeyman",
    family: "Défense",
    skydust: "3",
    gem_slots: "0",
    slot_type: "Arme",
    slot_name: "Épée",
    skill_1: "Recycleur",
    value_1_pct: "0",
    skill_2: "Bravoure",
    value_2_pct: "0",
    skill_3: "Défense",
    value_3_pct: "3",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Commun",
    set_name: "Journeyman",
    family: "Défense",
    skydust: "3",
    gem_slots: "0",
    slot_type: "Bouclier",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "0",
    skill_2: "Bravoure",
    value_2_pct: "0",
    skill_3: "Défense",
    value_3_pct: "3",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Commun",
    set_name: "Journeyman",
    family: "Défense",
    skydust: "3",
    gem_slots: "0",
    slot_type: "Ceinture",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "0",
    skill_2: "Bravoure",
    value_2_pct: "0",
    skill_3: "Défense",
    value_3_pct: "3",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Commun",
    set_name: "Journeyman",
    family: "Défense",
    skydust: "3",
    gem_slots: "0",
    slot_type: "Anneau",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "1",
    skill_2: "Bravoure",
    value_2_pct: "0",
    skill_3: "Défense",
    value_3_pct: "0",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Commun",
    set_name: "Journeyman",
    family: "Défense",
    skydust: "3",
    gem_slots: "0",
    slot_type: "Bracelet",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "1",
    skill_2: "Bravoure",
    value_2_pct: "0",
    skill_3: "Défense",
    value_3_pct: "0",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Commun",
    set_name: "Journeyman",
    family: "Défense",
    skydust: "3",
    gem_slots: "0",
    slot_type: "Amulette",
    slot_name: "",
    skill_1: "Recycleur",
    value_1_pct: "1",
    skill_2: "Bravoure",
    value_2_pct: "0",
    skill_3: "Défense",
    value_3_pct: "0",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Commun",
    set_name: "Barbarian",
    family: "Attaque",
    skydust: "3",
    gem_slots: "0",
    slot_type: "Arme",
    slot_name: "Hache",
    skill_1: "Attaque",
    value_1_pct: "2",
    skill_2: "Charognard",
    value_2_pct: "0",
    skill_3: "Intrépide",
    value_3_pct: "0",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Commun",
    set_name: "Barbarian",
    family: "Attaque",
    skydust: "3",
    gem_slots: "0",
    slot_type: "Bouclier",
    slot_name: "",
    skill_1: "Attaque",
    value_1_pct: "2",
    skill_2: "Charognard",
    value_2_pct: "0",
    skill_3: "Intrépide",
    value_3_pct: "0",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Commun",
    set_name: "Barbarian",
    family: "Attaque",
    skydust: "3",
    gem_slots: "0",
    slot_type: "Ceinture",
    slot_name: "",
    skill_1: "Attaque",
    value_1_pct: "2",
    skill_2: "Charognard",
    value_2_pct: "0",
    skill_3: "Intrépide",
    value_3_pct: "0",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Commun",
    set_name: "Barbarian",
    family: "Attaque",
    skydust: "3",
    gem_slots: "0",
    slot_type: "Anneau",
    slot_name: "",
    skill_1: "Attaque",
    value_1_pct: "0",
    skill_2: "Charognard",
    value_2_pct: "2",
    skill_3: "Intrépide",
    value_3_pct: "0",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Commun",
    set_name: "Barbarian",
    family: "Attaque",
    skydust: "3",
    gem_slots: "0",
    slot_type: "Bracelet",
    slot_name: "",
    skill_1: "Attaque",
    value_1_pct: "0",
    skill_2: "Charognard",
    value_2_pct: "2",
    skill_3: "Intrépide",
    value_3_pct: "0",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Commun",
    set_name: "Barbarian",
    family: "Attaque",
    skydust: "3",
    gem_slots: "0",
    slot_type: "Amulette",
    slot_name: "",
    skill_1: "Attaque",
    value_1_pct: "0",
    skill_2: "Charognard",
    value_2_pct: "2",
    skill_3: "Intrépide",
    value_3_pct: "0",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Commun",
    set_name: "Barbarian",
    family: "Attaque",
    skydust: "3",
    gem_slots: "0",
    slot_type: "Casque",
    slot_name: "",
    skill_1: "Attaque",
    value_1_pct: "",
    skill_2: "Charognard",
    value_2_pct: "",
    skill_3: "Intrépide",
    value_3_pct: "",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Commun",
    set_name: "Barbarian",
    family: "Attaque",
    skydust: "3",
    gem_slots: "0",
    slot_type: "Gantelet",
    slot_name: "",
    skill_1: "Attaque",
    value_1_pct: "",
    skill_2: "Charognard",
    value_2_pct: "",
    skill_3: "Intrépide",
    value_3_pct: "4",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Commun",
    set_name: "Barbarian",
    family: "Attaque",
    skydust: "3",
    gem_slots: "0",
    slot_type: "Bottes",
    slot_name: "",
    skill_1: "Attaque",
    value_1_pct: "",
    skill_2: "Charognard",
    value_2_pct: "",
    skill_3: "Intrépide",
    value_3_pct: "2",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Rare",
    set_name: "Hunter",
    family: "Troupes/Vitesse",
    skydust: "10",
    gem_slots: "0",
    slot_type: "Casque",
    slot_name: "",
    skill_1: "Recruteur",
    value_1_pct: "3",
    skill_2: "Intrépide",
    value_2_pct: "4",
    skill_3: "Bravoure",
    value_3_pct: "",
    skill_4: "Vitesse",
    value_4_pct: "",
  },
  {
    rarity: "Rare",
    set_name: "Hunter",
    family: "Troupes/Vitesse",
    skydust: "10",
    gem_slots: "0",
    slot_type: "Gantelet",
    slot_name: "",
    skill_1: "Recruteur",
    value_1_pct: "3",
    skill_2: "Intrépide",
    value_2_pct: "4",
    skill_3: "Bravoure",
    value_3_pct: "",
    skill_4: "Vitesse",
    value_4_pct: "",
  },
  {
    rarity: "Rare",
    set_name: "Hunter",
    family: "Troupes/Vitesse",
    skydust: "10",
    gem_slots: "0",
    slot_type: "Bottes",
    slot_name: "",
    skill_1: "Recruteur",
    value_1_pct: "3",
    skill_2: "Intrépide",
    value_2_pct: "4",
    skill_3: "Bravoure",
    value_3_pct: "",
    skill_4: "Vitesse",
    value_4_pct: "",
  },
  {
    rarity: "Commun",
    set_name: "Bard",
    family: "Troupes/Vitesse",
    skydust: "3",
    gem_slots: "0",
    slot_type: "Casque",
    slot_name: "",
    skill_1: "Inconnu",
    value_1_pct: "",
    skill_2: "",
    value_2_pct: "",
    skill_3: "",
    value_3_pct: "",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Commun",
    set_name: "Bard",
    family: "Troupes/Vitesse",
    skydust: "3",
    gem_slots: "0",
    slot_type: "Gantelet",
    slot_name: "",
    skill_1: "Inconnu",
    value_1_pct: "",
    skill_2: "",
    value_2_pct: "",
    skill_3: "",
    value_3_pct: "",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Commun",
    set_name: "Bard",
    family: "Troupes/Vitesse",
    skydust: "3",
    gem_slots: "0",
    slot_type: "Bottes",
    slot_name: "",
    skill_1: "Inconnu",
    value_1_pct: "",
    skill_2: "",
    value_2_pct: "",
    skill_3: "",
    value_3_pct: "",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Commun",
    set_name: "Journeyman",
    family: "Défense",
    skydust: "3",
    gem_slots: "0",
    slot_type: "Casque",
    slot_name: "",
    skill_1: "Inconnu",
    value_1_pct: "",
    skill_2: "",
    value_2_pct: "",
    skill_3: "",
    value_3_pct: "",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Commun",
    set_name: "Journeyman",
    family: "Défense",
    skydust: "3",
    gem_slots: "0",
    slot_type: "Gantelet",
    slot_name: "",
    skill_1: "Inconnu",
    value_1_pct: "",
    skill_2: "",
    value_2_pct: "",
    skill_3: "",
    value_3_pct: "",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Commun",
    set_name: "Journeyman",
    family: "Défense",
    skydust: "3",
    gem_slots: "0",
    slot_type: "Bottes",
    slot_name: "",
    skill_1: "Inconnu",
    value_1_pct: "",
    skill_2: "",
    value_2_pct: "",
    skill_3: "",
    value_3_pct: "",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Commun",
    set_name: "Thief",
    family: "Or",
    skydust: "3",
    gem_slots: "0",
    slot_type: "Casque",
    slot_name: "",
    skill_1: "Inconnu",
    value_1_pct: "",
    skill_2: "",
    value_2_pct: "",
    skill_3: "",
    value_3_pct: "",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Commun",
    set_name: "Thief",
    family: "Or",
    skydust: "3",
    gem_slots: "0",
    slot_type: "Gantelet",
    slot_name: "",
    skill_1: "Inconnu",
    value_1_pct: "",
    skill_2: "",
    value_2_pct: "",
    skill_3: "",
    value_3_pct: "",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Commun",
    set_name: "Thief",
    family: "Or",
    skydust: "3",
    gem_slots: "0",
    slot_type: "Bottes",
    slot_name: "",
    skill_1: "Inconnu",
    value_1_pct: "",
    skill_2: "",
    value_2_pct: "",
    skill_3: "",
    value_3_pct: "",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Rare",
    set_name: "Adventurer",
    family: "Défense",
    skydust: "10",
    gem_slots: "0",
    slot_type: "Casque",
    slot_name: "",
    skill_1: "Inconnu",
    value_1_pct: "",
    skill_2: "",
    value_2_pct: "",
    skill_3: "",
    value_3_pct: "",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Rare",
    set_name: "Adventurer",
    family: "Défense",
    skydust: "10",
    gem_slots: "0",
    slot_type: "Gantelet",
    slot_name: "",
    skill_1: "Inconnu",
    value_1_pct: "",
    skill_2: "",
    value_2_pct: "",
    skill_3: "",
    value_3_pct: "",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Rare",
    set_name: "Adventurer",
    family: "Défense",
    skydust: "10",
    gem_slots: "0",
    slot_type: "Bottes",
    slot_name: "",
    skill_1: "Inconnu",
    value_1_pct: "",
    skill_2: "",
    value_2_pct: "",
    skill_3: "",
    value_3_pct: "",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Rare",
    set_name: "Smuggler",
    family: "Or",
    skydust: "10",
    gem_slots: "0",
    slot_type: "Casque",
    slot_name: "",
    skill_1: "Inconnu",
    value_1_pct: "",
    skill_2: "",
    value_2_pct: "",
    skill_3: "",
    value_3_pct: "",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Rare",
    set_name: "Smuggler",
    family: "Or",
    skydust: "10",
    gem_slots: "0",
    slot_type: "Gantelet",
    slot_name: "",
    skill_1: "Inconnu",
    value_1_pct: "",
    skill_2: "",
    value_2_pct: "",
    skill_3: "",
    value_3_pct: "",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Rare",
    set_name: "Smuggler",
    family: "Or",
    skydust: "10",
    gem_slots: "0",
    slot_type: "Bottes",
    slot_name: "",
    skill_1: "Inconnu",
    value_1_pct: "",
    skill_2: "",
    value_2_pct: "",
    skill_3: "",
    value_3_pct: "",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Rare",
    set_name: "Soldier",
    family: "Attaque",
    skydust: "10",
    gem_slots: "0",
    slot_type: "Casque",
    slot_name: "",
    skill_1: "Inconnu",
    value_1_pct: "",
    skill_2: "",
    value_2_pct: "",
    skill_3: "",
    value_3_pct: "",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Rare",
    set_name: "Soldier",
    family: "Attaque",
    skydust: "10",
    gem_slots: "0",
    slot_type: "Gantelet",
    slot_name: "",
    skill_1: "Inconnu",
    value_1_pct: "",
    skill_2: "",
    value_2_pct: "",
    skill_3: "",
    value_3_pct: "",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Rare",
    set_name: "Soldier",
    family: "Attaque",
    skydust: "10",
    gem_slots: "0",
    slot_type: "Bottes",
    slot_name: "",
    skill_1: "Inconnu",
    value_1_pct: "",
    skill_2: "",
    value_2_pct: "",
    skill_3: "",
    value_3_pct: "",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Épique",
    set_name: "Knight",
    family: "Défense",
    skydust: "30",
    gem_slots: "1",
    slot_type: "Casque",
    slot_name: "",
    skill_1: "Inconnu",
    value_1_pct: "",
    skill_2: "",
    value_2_pct: "",
    skill_3: "",
    value_3_pct: "",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Épique",
    set_name: "Knight",
    family: "Défense",
    skydust: "30",
    gem_slots: "1",
    slot_type: "Gantelet",
    slot_name: "",
    skill_1: "Inconnu",
    value_1_pct: "",
    skill_2: "",
    value_2_pct: "",
    skill_3: "",
    value_3_pct: "",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Épique",
    set_name: "Knight",
    family: "Défense",
    skydust: "30",
    gem_slots: "1",
    slot_type: "Bottes",
    slot_name: "",
    skill_1: "Inconnu",
    value_1_pct: "",
    skill_2: "",
    value_2_pct: "",
    skill_3: "",
    value_3_pct: "",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Épique",
    set_name: "Royal Archer",
    family: "Troupes/Vitesse",
    skydust: "30",
    gem_slots: "1",
    slot_type: "Casque",
    slot_name: "",
    skill_1: "Inconnu",
    value_1_pct: "",
    skill_2: "",
    value_2_pct: "",
    skill_3: "",
    value_3_pct: "",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Épique",
    set_name: "Royal Archer",
    family: "Troupes/Vitesse",
    skydust: "30",
    gem_slots: "1",
    slot_type: "Gantelet",
    slot_name: "",
    skill_1: "Inconnu",
    value_1_pct: "",
    skill_2: "",
    value_2_pct: "",
    skill_3: "",
    value_3_pct: "",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Épique",
    set_name: "Royal Archer",
    family: "Troupes/Vitesse",
    skydust: "30",
    gem_slots: "1",
    slot_type: "Bottes",
    slot_name: "",
    skill_1: "Inconnu",
    value_1_pct: "",
    skill_2: "",
    value_2_pct: "",
    skill_3: "",
    value_3_pct: "",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Épique",
    set_name: "Royal Guard",
    family: "Attaque",
    skydust: "30",
    gem_slots: "1",
    slot_type: "Casque",
    slot_name: "",
    skill_1: "Inconnu",
    value_1_pct: "",
    skill_2: "",
    value_2_pct: "",
    skill_3: "",
    value_3_pct: "",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Épique",
    set_name: "Royal Guard",
    family: "Attaque",
    skydust: "30",
    gem_slots: "1",
    slot_type: "Gantelet",
    slot_name: "",
    skill_1: "Inconnu",
    value_1_pct: "",
    skill_2: "",
    value_2_pct: "",
    skill_3: "",
    value_3_pct: "",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Épique",
    set_name: "Royal Guard",
    family: "Attaque",
    skydust: "30",
    gem_slots: "1",
    slot_type: "Bottes",
    slot_name: "",
    skill_1: "Inconnu",
    value_1_pct: "",
    skill_2: "",
    value_2_pct: "",
    skill_3: "",
    value_3_pct: "",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Épique",
    set_name: "Shopkeeper",
    family: "Or",
    skydust: "30",
    gem_slots: "1",
    slot_type: "Casque",
    slot_name: "",
    skill_1: "Inconnu",
    value_1_pct: "",
    skill_2: "",
    value_2_pct: "",
    skill_3: "",
    value_3_pct: "",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Épique",
    set_name: "Shopkeeper",
    family: "Or",
    skydust: "30",
    gem_slots: "1",
    slot_type: "Gantelet",
    slot_name: "",
    skill_1: "Inconnu",
    value_1_pct: "",
    skill_2: "",
    value_2_pct: "",
    skill_3: "",
    value_3_pct: "",
    skill_4: "",
    value_4_pct: "",
  },
  {
    rarity: "Épique",
    set_name: "Shopkeeper",
    family: "Or",
    skydust: "30",
    gem_slots: "1",
    slot_type: "Bottes",
    slot_name: "",
    skill_1: "Inconnu",
    value_1_pct: "",
    skill_2: "",
    value_2_pct: "",
    skill_3: "",
    value_3_pct: "",
    skill_4: "",
    value_4_pct: "",
  },
] as const;
