"use client";

import { EyeIcon, EyeOffIcon } from "lucide-react";
import { useRouter } from "next/navigation";
import { useTranslations } from "next-intl";
import { useId, useMemo, useState } from "react";
import { roles } from "@/auth/roles";
import { AdminButton } from "./admin-button";
import { ConfirmDialog } from "./admin-confirm-dialog";
import { DataTable, type AdminTableColumn } from "./admin-data-table";
import { OverflowMenu, type OverflowMenuItem } from "./admin-overflow-menu";
import { Pill, type PillTone } from "./admin-pill";
import { SidePanel } from "./admin-side-panel";
import { VisibilitySwitch } from "./admin-visibility-switch";

/**
 * Bloc 119: the Users screen.
 *
 * What it replaces: a creation form sitting above the table, a password field
 * on every single row (empty, permanently), and a role dropdown with nothing
 * to say what a role is for. Creation moves into a side panel, the password
 * into a dialog opened from the row, and each role now carries a sentence
 * computed from the permission matrix rather than written from memory.
 *
 * The three things an account may not do to itself — deactivate, delete,
 * change its own role — are enforced on the server (services/users.ts). Here
 * they are greyed out, so the rule is visible before it is hit.
 */

export type AdminUserRow = {
  id: string;
  username: string;
  role: string;
  active: boolean;
};

/**
 * Codex review (PR #148): a password field is masked. Both of these used to
 * be `type="password"` and lost it in the rewrite, which put a freshly
 * generated administrator credential in plain sight of anyone looking at the
 * screen — or of a screen share. Masked by default, with a reveal button,
 * because the admin does have to read a generated password once to hand it
 * over.
 */
function PasswordField({
  id,
  name,
  value,
  onChange,
  revealLabel,
  hideLabel,
}: {
  id: string;
  name?: string;
  value: string;
  onChange: (value: string) => void;
  revealLabel: string;
  hideLabel: string;
}) {
  const [revealed, setRevealed] = useState(false);
  return (
    <>
      <input
        id={id}
        name={name}
        type={revealed ? "text" : "password"}
        autoComplete="new-password"
        value={value}
        onChange={(event) => onChange(event.target.value)}
        className="admin-control admin-focus h-[var(--admin-control-h)] flex-1 rounded-admin-control border border-admin-card-border bg-admin-card px-3"
      />
      <AdminButton
        type="button"
        size="icon"
        variant="ghost"
        aria-pressed={revealed}
        aria-label={revealed ? hideLabel : revealLabel}
        onClick={() => setRevealed((current) => !current)}
      >
        {revealed ? (
          <EyeOffIcon aria-hidden="true" />
        ) : (
          <EyeIcon aria-hidden="true" />
        )}
      </AdminButton>
    </>
  );
}

/** The password policy the server enforces (services/users.ts). */
const passwordMinimumLength = 12;
const generatedPasswordLength = 20;
const passwordAlphabet =
  "abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789!@#$%&*?";

/**
 * A password the browser draws itself, from the platform CSPRNG — it is never
 * requested from, or generated by, the server (Bloc 119 §4). The alphabet
 * drops the characters that are read wrong out of a chat window (l/I/1,
 * O/0).
 */
function generatePassword(): string {
  const bytes = new Uint32Array(generatedPasswordLength);
  crypto.getRandomValues(bytes);
  return [...bytes]
    .map((value) => passwordAlphabet[value % passwordAlphabet.length])
    .join("");
}

const roleTone = (role: string): PillTone =>
  role === "super_admin"
    ? "accent-deep"
    : role === "admin"
      ? "accent"
      : "neutral";

export function AdminUsersList({
  rows,
  currentUserId,
  roleDescriptions,
  canManage,
}: {
  rows: AdminUserRow[];
  /** The signed-in account: its own row is protected. */
  currentUserId: string;
  /** One sentence per role, computed from the matrix by the page. */
  roleDescriptions: Record<string, string>;
  canManage: boolean;
}) {
  const t = useTranslations("admin.users");
  const router = useRouter();
  const roleLabels = useTranslations("roles");
  const [users, setUsers] = useState(rows);
  const [message, setMessage] = useState("");
  const [success, setSuccess] = useState(false);
  const [creating, setCreating] = useState(false);
  const [busy, setBusy] = useState(false);
  const [newUsername, setNewUsername] = useState("");
  const [newPassword, setNewPassword] = useState("");
  const [newRole, setNewRole] = useState("read_only");
  const [passwordFor, setPasswordFor] = useState<AdminUserRow>();
  const [newRowPassword, setNewRowPassword] = useState("");
  const [pendingDelete, setPendingDelete] = useState<AdminUserRow>();
  const usernameId = useId();
  const passwordId = useId();
  const rowPasswordId = useId();

  const report = (ok: boolean, text: string) => {
    setSuccess(ok);
    setMessage(text);
  };

  async function send(url: string, init: RequestInit) {
    try {
      const response = await fetch(url, init);
      if (!response.ok)
        report(false, `${t("error")} (HTTP ${response.status})`);
      return response.ok;
    } catch {
      report(false, t("server-error"));
      return false;
    }
  }

  async function create() {
    if (newPassword.length < passwordMinimumLength)
      return report(false, t("password-too-short"));
    setBusy(true);
    let created: AdminUserRow | undefined;
    try {
      const response = await fetch("/api/admin/users", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({
          username: newUsername,
          password: newPassword,
          role: newRole,
        }),
      });
      if (!response.ok) {
        report(false, `${t("error")} (HTTP ${response.status})`);
        return;
      }
      const body = (await response.json()) as {
        id: string;
        username: string;
        role: string;
      };
      created = { ...body, active: true };
    } catch {
      report(false, t("server-error"));
      return;
    } finally {
      setBusy(false);
    }
    // The row is added from what the route answers — its id comes from the
    // database — rather than waiting for a re-render: this list holds its
    // rows in state, so a router.refresh() alone would update the sidebar's
    // counter and leave the table one row behind (caught in e2e).
    setUsers((current) =>
      [...current, created].sort((a, b) =>
        a.username.localeCompare(b.username),
      ),
    );
    report(true, t("created"));
    setCreating(false);
    setNewUsername("");
    setNewPassword("");
    setNewRole("read_only");
    // …and the counters the server renders around it follow.
    router.refresh();
  }

  async function setActive(user: AdminUserRow, active: boolean) {
    const ok = await send(`/api/admin/users/${user.id}`, {
      method: "PATCH",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ active }),
    });
    if (!ok) return;
    setUsers((current) =>
      current.map((item) => (item.id === user.id ? { ...item, active } : item)),
    );
    report(true, t(active ? "activated" : "deactivated"));
  }

  async function setRole(user: AdminUserRow, role: string) {
    const ok = await send(`/api/admin/users/${user.id}`, {
      method: "PATCH",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ role }),
    });
    if (!ok) return;
    setUsers((current) =>
      current.map((item) => (item.id === user.id ? { ...item, role } : item)),
    );
    report(true, t("saved"));
  }

  async function changePassword() {
    if (!passwordFor) return;
    if (newRowPassword.length < passwordMinimumLength)
      return report(false, t("password-too-short"));
    setBusy(true);
    const ok = await send(`/api/admin/users/${passwordFor.id}`, {
      method: "PATCH",
      headers: { "content-type": "application/json" },
      body: JSON.stringify({ password: newRowPassword }),
    });
    setBusy(false);
    if (!ok) return;
    report(true, t("saved"));
    setPasswordFor(undefined);
    setNewRowPassword("");
  }

  async function remove(user: AdminUserRow) {
    setBusy(true);
    const ok = await send(`/api/admin/users/${user.id}`, { method: "DELETE" });
    setBusy(false);
    setPendingDelete(undefined);
    if (!ok) return;
    setUsers((current) => current.filter((item) => item.id !== user.id));
    report(true, t("deleted"));
  }

  const columns: AdminTableColumn<AdminUserRow>[] = useMemo(
    () => [
      {
        key: "user",
        header: t("columns-user"),
        cell: (user) => (
          <span className="flex items-center gap-3">
            <span
              aria-hidden="true"
              className="grid size-8 shrink-0 place-items-center rounded-full bg-admin-accent-soft text-xs font-semibold text-admin-accent-soft-ink"
            >
              {user.username.charAt(0).toLocaleUpperCase()}
            </span>
            <span className="font-semibold">{user.username}</span>
            {user.id === currentUserId && (
              <span className="text-xs text-admin-dim">{t("you")}</span>
            )}
          </span>
        ),
      },
      {
        key: "role",
        header: t("columns-role"),
        cell: (user) =>
          canManage && user.id !== currentUserId ? (
            <select
              aria-label={t("role")}
              value={user.role}
              onChange={(event) => setRole(user, event.target.value)}
              className="admin-control admin-focus h-[var(--admin-control-h-sm)] rounded-admin-control border border-admin-card-border bg-admin-card px-2 text-sm"
            >
              {roles.map((role) => (
                <option key={role} value={role}>
                  {roleLabels(role)}
                </option>
              ))}
            </select>
          ) : (
            // Own row, or a role that may only look: the pill, never a
            // control that would be refused by the server anyway.
            <Pill tone={roleTone(user.role)}>{roleLabels(user.role)}</Pill>
          ),
      },
      {
        key: "status",
        header: t("columns-status"),
        narrow: true,
        cell: (user) => (
          <VisibilitySwitch
            checked={user.active}
            disabled={!canManage || user.id === currentUserId}
            labels={{ on: t("active"), off: t("inactive") }}
            label={t("visibility-of", { username: user.username })}
            onChange={(next) => setActive(user, next)}
          />
        ),
      },
    ],
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [users, canManage, currentUserId],
  );

  const menuItems = (user: AdminUserRow): OverflowMenuItem[] => [
    {
      key: "deactivate",
      label: t(user.active ? "deactivate" : "activate"),
      disabled: user.id === currentUserId,
      onSelect: () => setActive(user, !user.active),
    },
    {
      key: "delete",
      label: `${t("delete")}…`,
      tone: "danger",
      disabled: user.id === currentUserId,
      onSelect: () => setPendingDelete(user),
    },
  ];

  return (
    <div className="flex flex-col gap-4">
      {canManage && (
        <div className="flex justify-end">
          <AdminButton
            type="button"
            variant="primary"
            onClick={() => setCreating(true)}
          >
            {t("new")}
          </AdminButton>
        </div>
      )}

      <div className="overflow-hidden rounded-admin-card border border-admin-card-border bg-admin-card">
        <DataTable
          caption={t("table-caption")}
          columns={columns}
          rows={users}
          rowKey={(user) => user.id}
          empty={t("no-results")}
          actions={{
            header: t("columns-actions"),
            cell: (user) =>
              canManage ? (
                <span className="inline-flex items-center gap-2">
                  <AdminButton
                    type="button"
                    size="sm"
                    onClick={() => {
                      setNewRowPassword("");
                      setPasswordFor(user);
                    }}
                  >
                    {t("change-password")}
                  </AdminButton>
                  <OverflowMenu
                    label={t("more-actions", { username: user.username })}
                    items={menuItems(user)}
                  />
                </span>
              ) : null,
            explain: () => t("self-protected"),
          }}
        />
      </div>

      {message && (
        <p
          role="status"
          className={
            success
              ? "text-sm text-admin-ok-ink"
              : "text-sm text-admin-danger-ink"
          }
        >
          {message}
        </p>
      )}

      <SidePanel
        open={creating}
        title={t("new")}
        description={t("new-panel-description")}
        onClose={() => setCreating(false)}
        footer={
          <AdminButton
            type="button"
            variant="primary"
            disabled={busy}
            onClick={create}
          >
            {t("create")}
          </AdminButton>
        }
      >
        <div className="flex flex-col gap-4">
          <label className="flex flex-col gap-1 text-sm" htmlFor={usernameId}>
            {t("username")}
            <input
              id={usernameId}
              name="username"
              value={newUsername}
              onChange={(event) => setNewUsername(event.target.value)}
              className="admin-control admin-focus h-[var(--admin-control-h)] rounded-admin-control border border-admin-card-border bg-admin-card px-3"
            />
          </label>
          <div className="flex flex-col gap-1 text-sm">
            <label htmlFor={passwordId}>{t("password")}</label>
            <div className="flex gap-2">
              <PasswordField
                id={passwordId}
                name="password"
                value={newPassword}
                onChange={setNewPassword}
                revealLabel={t("show-password")}
                hideLabel={t("hide-password")}
              />
              <AdminButton
                type="button"
                onClick={() => {
                  setNewPassword(generatePassword());
                  report(true, t("generated"));
                }}
              >
                {t("generate")}
              </AdminButton>
            </div>
            <span className="text-xs text-admin-dim">{t("password-hint")}</span>
          </div>
          <fieldset className="flex flex-col gap-2">
            <legend className="admin-eyebrow pb-1 text-admin-dim">
              {t("role")}
            </legend>
            {roles.map((role) => (
              <label
                key={role}
                className="flex cursor-pointer gap-3 rounded-admin-control border border-admin-card-border p-3 text-sm has-checked:border-admin-accent has-checked:bg-admin-accent-soft"
              >
                <input
                  type="radio"
                  name="role"
                  value={role}
                  checked={newRole === role}
                  onChange={() => setNewRole(role)}
                  className="admin-focus mt-1"
                />
                <span className="flex flex-col">
                  <span className="font-semibold">{roleLabels(role)}</span>
                  <span className="text-xs text-admin-dim">
                    {roleDescriptions[role]}
                  </span>
                </span>
              </label>
            ))}
          </fieldset>
        </div>
      </SidePanel>

      <SidePanel
        open={passwordFor !== undefined}
        title={t("change-password-title", {
          username: passwordFor?.username ?? "",
        })}
        onClose={() => setPasswordFor(undefined)}
        footer={
          <AdminButton
            type="button"
            variant="primary"
            disabled={busy}
            onClick={changePassword}
          >
            {t("change-password-confirm")}
          </AdminButton>
        }
      >
        <div className="flex flex-col gap-1 text-sm">
          <label htmlFor={rowPasswordId}>{t("password")}</label>
          <div className="flex gap-2">
            <PasswordField
              id={rowPasswordId}
              value={newRowPassword}
              onChange={setNewRowPassword}
              revealLabel={t("show-password")}
              hideLabel={t("hide-password")}
            />
            <AdminButton
              type="button"
              onClick={() => {
                setNewRowPassword(generatePassword());
                report(true, t("generated"));
              }}
            >
              {t("generate")}
            </AdminButton>
          </div>
          <span className="text-xs text-admin-dim">{t("password-hint")}</span>
        </div>
      </SidePanel>

      <ConfirmDialog
        open={pendingDelete !== undefined}
        title={t("delete-title")}
        description={t("delete-body", {
          username: pendingDelete?.username ?? "",
        })}
        confirmLabel={t("delete")}
        busy={busy}
        onCancel={() => setPendingDelete(undefined)}
        onConfirm={() => pendingDelete && remove(pendingDelete)}
      />
    </div>
  );
}
